### ISSUE TITLE
Only works if put as last module

### ISSUE THREAD

**Issue by Rigo-m** [dword-design/nuxt-route-meta#58]
I don't know if it's only on my project or in general. But while using `nuxt-route-meta` in conjunction with `@nuxtjs/composition-api`, by calling `useRoute` in SSR I noticed that it only works if put as last module. Don't have time now to try to reproduce. Is there any reason it could work only as last module?

**Comment by dword-design** [comment]
@Rigo-m hmm not that I know of. The module needs to have the routes ready so that it can call `this.extendRoutes` on them. Could it be that `@nuxtjs/composition-api` changes how routes are generated? If there are modules that generate routes somehow, I guess they need to be before `nuxt-route-meta`.

**Comment by dword-design** [comment]
Closing now. Feel free to reopen.
